# Generated by Django 5.0.7 on 2024-07-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalCoords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='PerevalLevels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winter', models.CharField(max_length=20)),
                ('summer', models.CharField(max_length=20)),
                ('autumn', models.CharField(max_length=20)),
                ('spring', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pereval_levels',
            },
        ),
        migrations.CreateModel(
            name='PerevalUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pereval_users',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beautyTitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('other_titles', models.CharField(max_length=200)),
                ('connect', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField()),
                ('images', models.JSONField()),
                ('id_coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalcoords')),
                ('id_levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevallevels')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalusers')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
    ]
