# Generated by Django 5.0.7 on 2024-07-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAddedImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pereval_added_images',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AlterField(
            model_name='perevalcoords',
            name='height',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perevalcoords',
            name='latitude',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perevalcoords',
            name='longitude',
            field=models.FloatField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='perevalusers',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_phone'),
        ),
        migrations.AddField(
            model_name='perevaladdedimages',
            name='id_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevaladded'),
        ),
        migrations.AddField(
            model_name='perevaladdedimages',
            name='id_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevalimages'),
        ),
    ]
