# Generated by Django 5.0.7 on 2024-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perevaladdedimages_perevalimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
