# Generated by Django 5.0.7 on 2024-07-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_perevalimages_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.perevalusers'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='project/media'),
        ),
    ]
